os: osx

install:
  - xcode-select --install
  - ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  - brew doctor
  - brew update
  - brew install python
  - brew install ansible

script:
  - ansible-playbook localhost.yml --check -vv -i hosts
