language: generic
os: osx
osx_image: xcode7.3 # El Capitan

matrix:
  include:
    - osx_image: xcode7.1      # Yosemite
    # - osx_image: beta-xcode6.2 # Mavericks

before_install:
  - brew update
  - sed -e 's/- brewcask/# - brewcask/' -e 's/- font/# - font/' localhost.yml > ci.yml

install:
  - xcode-select -p
  - xcode-select --switch /Library/Developer/CommandLineTools/
  - brew install ansible

script:
  - travis_wait 60 ansible-playbook ci.yml -vv -i hosts

after_script:
  - cat /tmp/php-build*
