language: generic
os: osx

matrix:
  include:
    - osx_image: xcode7.3      # El Capitan
    - osx_image: xcode7.1      # Yosemite
    - osx_image: beta-xcode6.2 # Mavericks

before_install:
  - brew update

install:
  - brew install ansible

script:
  - travis_wait 60 ansible-playbook localhost.yml -vv -i hosts

after_script:
  - git --version
  - brew doctor
  - brew cask doctor
