language: generic
os: osx
osx_image: beta-xcode6.2 # Mavericks

matrix:
  include:
    - osx_image: xcode7.3 # El Capitan
    - osx_image: xcode7.1 # Yosemite

before_install:
  - brew update
  - sed 's/- brewcask/# - brewcask/' localhost.yml > ci.yml

install:
  - brew install ansible

script:
  - travis_wait 60 ansible-playbook ci.yml -vv -i hosts

after_script:
  - git --version
  - brew doctor
  - brew cask doctor
