os: osx

before_install:
  - brew update

install:
  - brew install ansible

script:
  - travis_wait 30 ansible-playbook localhost.yml -vv -i hosts

after_script:
  - git --version
  - brew doctor
  - brew cask doctor
