- hosts: localhost
  connection: local
  gather_facts: no
  become: no
  roles:
    - osx
    - dotfiles
    - downloads
    - homebrew
    - brewcask
    - editor
    - font
    - docker
    - anyenv
    - php
    - go
    - ruby
    - nodejs
    - python
