- hosts: localhost
  connection: local
  gather_facts: no           
  become: no

  roles:
    - osx
    - dotfiles
    - downloads
    - homebrew
    - anyenv
    - php
    - go

  vars:
    homebrew_cask_packages:
      - { name: alfred }
      - { name: dash }
      - { name: flash-player }
      - { name: quicklook-csv }
      - { name: quicklook-json }
      - { name: heroku-toolbelt }
      - { name: adobe-creative-cloud }
      - { name: appcleaner }
      - { name: cyberduck }
      - { name: evernote }
      - { name: firefox }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: iterm2 }
      - { name: karabiner }
      - { name: mysqlworkbench }
      - { name: sequel-pro }
      - { name: sublime-text }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: xmind }
      - { name: spectacle }
      - { name: skype }
      - { name: recordit }
      - { name: coteditor }
      # Fonts
      # https://github.com/caskroom/homebrew-fonts/tree/master/Casks
      - { name: font-source-code-pro }
      - { name: font-source-han-code-jp }
    node_versions:
      - { version: v0.12.13 }
      - { version: v4.4.3, global: true }
      - { version: v5.10.1 }
    ruby_versions:
      - { version: 1.9.3-p551 }
      - { version: 2.3.0, global: true }
    npm_packages:
      - { name: babel-cli, global: true }
      - { name: bower, global: true }
      - { name: daff, global: true }
      - { name: faker-cli, global: true }
      - { name: release-changelog, global: true }
      - { name: yeoman, global: true }
    gem_packages:
      - bundler
      - sqlite3

  tasks:
    - name: Get os version
      shell: 'sw_vers | grep "10.[0-9]\{2\}"'
      register: newer_yosemite
      ignore_errors: true

    - name: Install Homebrew cask
      homebrew: name=brew-cask state=latest

    - name: Install node versions
      shell: source ~/.bashrc && ndenv install {{ item.version }}
      with_items: '{{ node_versions }}'

    - name: Install ruby versions
      shell: source ~/.bashrc && rbenv install {{ item.version }}
      with_items: '{{ ruby_versions }}'

    - name: Set node version to {{ item.version }}
      shell: source ~/.bashrc && ndenv install {{ item.version }}
      with_items: '{{ node_versions }}'
      when: '{{ item.global | default(False) }}'

    - name: Set ruby version to {{ item.version }}
      shell: source ~/.bashrc && rbenv install {{ item.version }}
      with_items: '{{ ruby_versions }}'
      when: '{{ item.global | default(False) }}'

    - name: Install gem packages
      gem: name={{ item }} state=latest
      with_items: '{{ gem_packages }}'

    - name: Install npm packages
      npm: >
        name={{ item.name }}
        production=yes
        global={{ item.global | default(False) }}
        state={{ item.state | default('latest') }}
      with_items: '{{ npm_packages }}'

    - name: Install Homebrew cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: '{{ homebrew_cask_packages }}'
      notify: brew cask doctor

  handlers:
    - name: brew cask doctor
      command: brew cask doctor
