- hosts: localhost
  connection: local
  gather_facts: no           
  become: no

  roles:
    - osx
    - dotfiles
    - downloads
    - homebrew
    - anyenv
    - php
    - go
    - ruby
    - nodejs

  vars:
    homebrew_cask_packages:
      - { name: alfred }
      - { name: dash }
      - { name: flash-player }
      - { name: quicklook-csv }
      - { name: quicklook-json }
      - { name: heroku-toolbelt }
      - { name: adobe-creative-cloud }
      - { name: appcleaner }
      - { name: cyberduck }
      - { name: evernote }
      - { name: firefox }
      - { name: google-chrome }
      - { name: google-japanese-ime }
      - { name: iterm2 }
      - { name: karabiner }
      - { name: mysqlworkbench }
      - { name: sequel-pro }
      - { name: sublime-text }
      - { name: vagrant }
      - { name: virtualbox }
      - { name: xmind }
      - { name: spectacle }
      - { name: skype }
      - { name: recordit }
      - { name: coteditor }
      # Fonts
      # https://github.com/caskroom/homebrew-fonts/tree/master/Casks
      - { name: font-source-code-pro }
      - { name: font-source-han-code-jp }

  tasks:
    - name: Get os version
      shell: 'sw_vers | grep "10.[0-9]\{2\}"'
      register: newer_yosemite
      ignore_errors: true

    - name: Install Homebrew cask
      homebrew: name=brew-cask state=latest

    - name: Install Homebrew cask packages
      homebrew_cask: name={{ item.name }} state={{ item.state|default('installed') }}
      with_items: '{{ homebrew_cask_packages }}'
      notify: brew cask doctor

  handlers:
    - name: brew cask doctor
      command: brew cask doctor
