homebrew_packages:
  - { name: bison, version: 2.7.1 }
  - { name: re2c }
  - { name: libjpeg }
  - { name: libpng }
  - { name: libmcrypt }
  - { name: autoconf }
php_versions:
  - { version: 5.6.20, global: true }
  - { version: 7.0.5 }
