- name: Check installed node versions
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && ndenv versions
  register: installed_versions

- name: Install node versions
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && ndenv install {{ item.version }}
  with_items: '{{ node_versions }}'
  when: "installed_versions.stdout.find('{{ item.version }}') == -1"

- name: Set node version to {{ item.version }}
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && ndenv global {{ item.version }}
  with_items: '{{ node_versions }}'
  when: '{{ item.global | default(False) }}'

- name: Install npm packages
  npm: >
    name={{ item.name }}
    production=yes
    executable=~/.anyenv/envs/ndenv/shims/npm
    global={{ item.global | default(False) }}
    state={{ item.state | default('latest') }}
  with_items: '{{ npm_packages }}'
