- name: Install node versions
  shell: source ~/.bashrc && ndenv install {{ item.version }}
  with_items: '{{ node_versions }}'

- name: Set node version to {{ item.version }}
  shell: source ~/.bashrc && ndenv global {{ item.version }}
  with_items: '{{ node_versions }}'
  when: '{{ item.global | default(False) }}'

- name: Install npm packages
  npm: >
    name={{ item.name }}
    production=yes
    global={{ item.global | default(False) }}
    state={{ item.state | default('latest') }}
  with_items: '{{ npm_packages }}'
