alfred_workflows:
  - 'https://raw.github.com/willfarrell/alfred-pkgman-workflow/master/Package%20Managers.alfredworkflow'
  - 'https://raw.github.com/willfarrell/alfred-caniuse-workflow/master/caniuse.alfredworkflow'
  - 'https://github.com/packal/repository/raw/master/com.cnsworder.vbox/vbox.alfredworkflow'
  - 'https://github.com/packal/repository/raw/master/tylereich.colors/colors_v2.0.1.alfredworkflow'
  - 'https://github.com/packal/repository/raw/master/mn.frd.alfred-dongers/dongers.alfredworkflow'
  - 'https://github.com/packal/repository/raw/master/dk.rodalgaard.alfred.network/network.alfredworkflow'
  - 'https://dl.dropboxusercontent.com/u/48987130/alfred_workflows/hatebu_for_alfred.alfredworkflow'
  - 'https://dl.dropboxusercontent.com/u/48987130/alfred_workflows/Markdown%20Link%20Generator.alfredworkflow'
  - 'https://github.com/packal/repository/raw/master/net.deanishe.alfred-stackoverflow/stackoverflow-1.2.alfredworkflow'
  - 'https://github.com/packal/repository/raw/master/com.ravelll.wifi/wi-fi.alfredworkflow'
downloads:
  - url: 'http://ethanschoonover.com/solarized/files/solarized.zip'
    dest: ~/Downloads
  - url: 'https://github.com/leothelocust/sequelpro-solarized-colorscheme/archive/master.zip'
    dest: ~/Downloads
