- name: Remove brew-cask
  homebrew: name=brew-cask state=absent

- name: Update Homebrew cask
  shell: brew update && brew cleanup && brew cask cleanup --outdated

- name: Install Homebrew cask packages
  homebrew_cask: name={{ item.name }} state={{ item.state | default('present') }}
  with_items: '{{ homebrew_cask_packages }}'
  notify: brew cask doctor
