- name: Install Homebrew cask packages
  homebrew_cask: name={{ item.name }} state={{ item.state | default('present') }}
  with_items: '{{ homebrew_cask_packages }}'
  notify:
    - brew cask doctor

- name: Clean up outdated Homebrew cask packages
  shell: brew cask cleanup --outdated
  register: brew_cask_cleanup_result
  changed_when: "brew_cask_cleanup_result.stdout.find('Nothing to do') != -1"
