- name: Remove brew-cask
  homebrew: name=brew-cask state=absent

- name: Install Homebrew cask packages
  homebrew_cask: name={{ item.name }} state={{ item.state|default('latest') }}
  with_items: '{{ homebrew_cask_packages }}'
  notify: brew cask doctor
