- name: Install php versions
  shell: source ~/.bashrc && phpenv install {{ item.version }}
  with_items: '{{ php_versions }}'

- name: Set php version to {{ item.version }}
  shell: source ~/.bashrc && phpenv install {{ item.version }}
  with_items: '{{ php_versions }}'
  when: '{{ item.global | default(False) }}'
