- name: Override php-build default settings
  template: >
    src={{ playbook_dir }}/roles/php/files/default_configure_options
    dest=~/.anyenv/envs/phpenv/plugins/php-build/share/php-build/default_configure_options
    force=yes
    mode=0644

- name: Link Homebrew packages
  homebrew: 'name={{ item.name }} state=linked'
  with_items: '{{ link_packages }}'

- name: Check installed php versions
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && phpenv versions
  register: installed_versions
  changed_when: false

- name: Check current php version
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && phpenv versions | grep '*' && awk '{print $2}'
  register: current_version
  changed_when: false

- name: Install php versions
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && phpenv install {{ item.version }}
  with_items: '{{ php_versions }}'
  when: "installed_versions.stdout.find('{{ item.version }}') == -1"

- name: Set php version to {{ item.version }}
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && phpenv global {{ item.version }}
  with_items: '{{ php_versions }}'
  when: '(current_version.rc != 0) or ({{ item.global | default(False) }} and "{{ item.version }}" == current_version)'

- name: Unlink Homebrew packages
  homebrew: 'name={{ item.name }} state=unlinked'
  with_items: '{{ link_packages }}'
