- name: Install php versions
  shell: source ~/.bashrc && PHP_BUILD_CONFIGURE_OPTS='--with-openssl=/usr/local/Cellar/openssl/1.0.2g' phpenv install {{ item.version }}
  with_items: '{{ php_versions }}'

- name: Set php version to {{ item.version }}
  shell: source ~/.bashrc && phpenv global {{ item.version }}
  with_items: '{{ php_versions }}'
  when: '{{ item.global | default(False) }}'
