- name: Override php-build default settings
  template: >
    src={{ playbook_dir }}/roles/php/files/default_configure_options
    dest=~/.anyenv/envs/phpenv/plugins/php-build/share/php-build/default_configure_options
    force=yes
    mode=0644

- name: Check installed php versions
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && phpenv versions
  register: installed_versions

- name: Install php versions
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && phpenv install {{ item.version }}
  with_items: '{{ php_versions }}'
  when: "installed_versions.stdout.find('{{ item.version }}') == -1"

- name: Set php version to {{ item.version }}
  shell: eval "$(~/.anyenv/bin/anyenv init -)" && phpenv global {{ item.version }}
  with_items: '{{ php_versions }}'
  when: '{{ item.global | default(False) }}'
