homebrew_packages:
  - { name: readline }
  - { name: openssl }
  - { name: bash }
  - { name: git }
  - { name: hub }
  - { name: cowsay }
  - { name: docker-compose }
  - { name: gnu-sed }
  - { name: graphviz }
  - { name: jq }
  - { name: mecab }
  - { name: mecab-ipadic }
  - { name: nkf }
  - { name: nmap }
  - { name: tree }
  - { name: unrar }
  - { name: vim }
  - { name: wget }
  - { name: coreutils }
  - { name: bash-completion }
  - { name: httpie }
  - { name: peco }
  - { name: argon/mas/mas }
  # For React native
  - { name: watchman }
  - { name: yarn }
  # For Brew cask
  - { name: brew-cask, state: absent, install_options: force }
  # For PHP
  - { name: bison27 }
  - { name: pcre }
  - { name: zlib }
  - { name: re2c }
  - { name: libjpeg }
  - { name: libpng }
  - { name: libmcrypt }
  - { name: autoconf }
  - { name: automake }
  # You have unlinked kegs in your Cellar...
  # - { name: ppl011 }
  # - { name: ppl011, state: linked }
